version: '3'
services:
  bootstrap_db:
    depends_on:
      - postgres
    image: postgres
    volumes:
      - "./init.sql:/tmp/init.sql"
    env_file:
      - ${ENV_FILE:env}
    command: ["psql", "-f", "/tmp/init.sql"]
  publisher:
    depends_on:
      - kafka
    env_file:
      - ${ENV_FILE:env}
    build:
      context: .
    image: publisher:17
    command: ["python", "publisher.py"]
  subscriber:
    volumes:
      - "/tmp:/tmp/"
    env_file:
      - ${ENV_FILE:env}
    depends_on:
      - bootstrap_db
      - kafka
    build:
      context: .
    image: subscriber:17
    command: ["python", "subscriber.py"]