version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aiven
  bootstrap_db:
    depends_on:
      - postgres
    image: postgres
    volumes:
      - "./init.sql:/tmp/init.sql"
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: aiven
    command: ["psql", "-f", "/tmp/init.sql"]
  publisher:
    build:
      context: .
    image: publisher:7
    command: ["python", "publisher.py"]
  subscriber:
    depends_on:
      - bootstrap_db
    build:
      context: .
    image: subscriber:7
    command: ["python", "subscriber.py"]